language: python
python:
  - 3.6

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/test_l2.py
  - python -m unittest tests/test_recovery.py
  - python -m unittest tests/test_omp.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: master